name: Deploy

on:
  push:
    branches:
      - gh-pages 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Bun
        uses: DeMoorJasper/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies and build
        run: |
          cd page 
          bun install
          bun run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./page/dist  
